### ISSUE TITLE
Not compatible with Zotero Standalone

### ISSUE THREAD

**Issue by dowcet** [corajr/zotero-prevent-duplicates#4]
I just used the shell script on a Linux machine to generate an .xpi file, but when I tried to install it I got the following message: "The add-on "Prevent Duplicates Plugin for Zotero" could not be installed. It may be incompatible with this version of Zotero Standalone." The Zotero version number is 4.0.17.

**Comment by zjays** [comment]
This can be made compatible with Zotero Standalone if you edit install.rdf and change the maxversion value for Zotero from 3.0.* to 4.* before zipping/creating the .xpi file.
I was able to install this as an add-on to Zotero Standalone after doing the above procedure, but it doesn't seem to detect duplicates when I use it with Zotero for Firefox in connector mode. Maybe because the add-on within Firefox is now disabled because it is not verified?

**Comment by redapemusic35** [comment]
Update on previous answer: Change maxversion value for Zotero from 3.0.* to 5.0.* before zipping/creating the .xpi file.
